namespace Synergos.CMS.Application.Dto.Constants;

/// <summary>
/// Stable GUID keys for Umbraco Content Types (Compositions, Element
/// Types, Document Types) that have been exported to
/// <c>Synergos.CMS.Web/uSync/v9/ContentTypes/</c>.
/// </summary>
/// <remarks>
/// Per ADR 0008, uSync XMLs are the source of truth; this class is a
/// typed reference for code that needs to resolve types by GUID.
///
/// GUID assignment policy:
/// <list type="bullet">
///   <item>GUIDs are <b>generated by Umbraco</b> when the type is
///   created in the backoffice. uSync captures the value on export
///   (feature <c>feedback_no_preassigned_guids_usync</c> in agent memory).</item>
///   <item>Constants are added here <b>after</b> the uSync XML exists —
///   never before. The quadruple verification from
///   <c>MIGRATION_GUARDRAILS §6.2</c> runs on the real captured GUID.</item>
///   <item>The Epic Fail 2 prefix convention (<c>b1*-b8*</c> Compositions,
///   <c>c3*-ce*</c> Element Types, <c>d2*-d6*</c> Document Types) is a
///   <b>historical reference</b> (see <c>history_guid_registry_epicfail2</c>
///   in agent memory), not a rule. Current GUIDs are whatever Umbraco
///   generates; no attempt to force them into legacy ranges.</item>
/// </list>
/// </remarks>
public static class ContentTypeKeys
{
    /// <summary>
    /// <c>compSeo</c> — Composition providing the <c>seoTitle</c>
    /// property. Composed into Document Types that need SEO metadata;
    /// not instantiable as Content (<c>IsElement=false</c>).
    /// </summary>
    /// <remarks>
    /// Source: <c>Synergos.CMS.Web/uSync/v9/ContentTypes/compseo.config</c>.
    /// GUID generated by Umbraco on backoffice save (Ola 4 of the
    /// migration plan). Minor visual-naming debt tracked in
    /// <c>refactor-docs/migration/03-migration-inventory.md</c>
    /// (Ola 4 execution log) — does not affect the contract of the
    /// alias / GUID used from code.
    /// </remarks>
    public static readonly Guid CompSeo =
        Guid.Parse("85e75635-b950-4583-b5ca-2a51c08892e3");

    /// <summary>
    /// <c>pageBasic</c> — Minimal Document Type (ADR 0014). Smoke test
    /// for the RenderController → Response DTO → Razor Template
    /// pipeline. Composes <see cref="CompSeo"/> for <c>seoTitle</c> and
    /// adds a single richtext <c>body</c> property.
    /// </summary>
    /// <remarks>
    /// Source: <c>Synergos.CMS.Web/uSync/v9/ContentTypes/page-basic.config</c>.
    /// GUID generated fresh by the agent (Flow B — agent-authored XML,
    /// see <c>feedback_no_preassigned_guids_usync</c>) with quadruple
    /// verification pre-commit (MIGRATION_GUARDRAILS §6.2). Import into
    /// the DB happens when the architect runs <c>uSync Import</c> in
    /// the backoffice.
    /// </remarks>
    public static readonly Guid PageBasic =
        Guid.Parse("95fef9ef-a6b2-454d-af54-b58d03b2a88e");

    /// <summary>
    /// <c>compCoreBase</c> — Base composition for technical metadata
    /// (e.g. <c>internalNotes</c>). Composed into every core DocType.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcorebase.config</c>.
    /// Flow B (agent-authored) — Ola 8.
    /// </remarks>
    public static readonly Guid CompCoreBase =
        Guid.Parse("5e2ec6b8-7f65-4c26-8c20-1b9a72bed2f8");

    /// <summary>
    /// <c>compCoreLifecycle</c> — Editorial lifecycle metadata
    /// (<c>publishingNotes</c>). Composed into DocTypes that need
    /// formal editorial traceability.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcorelifecycle.config</c>.
    /// Flow B — Ola 8.
    /// </remarks>
    public static readonly Guid CompCoreLifecycle =
        Guid.Parse("77440708-6cce-4a20-8679-212aaadd92eb");

    /// <summary>
    /// <c>siteRoot</c> — Top-level site container. One per
    /// brand/deployment (multi-brand handled in a later wave).
    /// Hosts pageBase, pageBare and pageBasic as children.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/siteroot.config</c>.
    /// Flow B — Ola 8.
    /// </remarks>
    public static readonly Guid SiteRoot =
        Guid.Parse("03d85835-06e4-4d8b-bd18-6088a529cf57");

    /// <summary>
    /// <c>pageBase</c> — Canonical editorial page under siteRoot.
    /// Composes compCoreBase + compCoreLifecycle + compSeo. Adds a
    /// richtext <c>body</c>.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/page-base.config</c>.
    /// Flow B — Ola 8.
    /// </remarks>
    public static readonly Guid PageBase =
        Guid.Parse("b4df602f-1c16-4ad7-8b57-69aa64ff6ad1");

    /// <summary>
    /// <c>pageBare</c> — Chrome-less page variant. Composes
    /// compCoreBase + compSeo. Template emits only the body without
    /// shared layout chrome.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/page-bare.config</c>.
    /// Flow B — Ola 8.
    /// </remarks>
    public static readonly Guid PageBare =
        Guid.Parse("0bd9379d-07eb-49de-802a-e68483322582");

    /// <summary>
    /// <c>compIntegration</c> — Base composition for elements that
    /// integrate an external artifact: SynHost blocks (CDN-backed),
    /// iframe hosts, script hosts. Provides a <c>configOverride</c>
    /// JSON field. Variations=Nothing.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compintegration.config</c>.
    /// Flow B (agent-authored) — Ola 8.5.
    /// </remarks>
    public static readonly Guid CompIntegration =
        Guid.Parse("84fe7a74-faa4-434f-acf1-b1ae1a50a90f");

    /// <summary>
    /// <c>elementIntIframeHost</c> — Element Type for embedding an
    /// iframe from an external origin (YouTube, Vimeo, Typeform, etc.).
    /// Not a CDN block; use <c>elementSyn*</c> for those.
    /// Variations=Culture.
    /// </summary>
    public static readonly Guid ElementIntIframeHost =
        Guid.Parse("5fe3cde6-a3b1-4afe-a5a4-a3730594ef29");

    /// <summary>
    /// <c>elementIntScriptHost</c> — Element Type for injecting a
    /// <c>&lt;script&gt;</c> from an allowlisted origin
    /// (<c>Synergos:Cdn:AllowedScriptOrigins</c> in appsettings).
    /// Variations=Nothing.
    /// </summary>
    public static readonly Guid ElementIntScriptHost =
        Guid.Parse("7c9b40d5-61f5-4b61-a4e3-79f14e9c7ef6");

    /// <summary>
    /// <c>elementSynAvatar</c> — SynHost pilot block. DOM:
    /// <c>&lt;synergos-avatar&gt;</c>. Bundle resolved at runtime via
    /// <see cref="Interfaces.IBundleRegistryClient"/>.
    /// </summary>
    public static readonly Guid ElementSynAvatar =
        Guid.Parse("28d5b6b8-200c-43a4-872a-d8958a392d97");

    /// <summary>
    /// <c>elementSynBadge</c> — SynHost pilot block. DOM:
    /// <c>&lt;synergos-badge&gt;</c>.
    /// </summary>
    public static readonly Guid ElementSynBadge =
        Guid.Parse("26965c38-03f5-44b2-a3e8-8daa5288143c");

    /// <summary>
    /// <c>elementSynDivider</c> — SynHost pilot block. DOM:
    /// <c>&lt;synergos-divider&gt;</c>. No own props; configurable
    /// only via <c>configOverride</c>.
    /// </summary>
    public static readonly Guid ElementSynDivider =
        Guid.Parse("e522308f-8591-4974-9a2f-b62dae8690fb");

    /// <summary>
    /// <c>compContentHeading</c> — Reusable heading composition
    /// (<c>headingTitle</c> + <c>headingSubtitle</c>). Composed into
    /// Element Types that need a typed header. Variations=Culture.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcontentheading.config</c>.
    /// Flow B — Ola 9. Folder <c>Compositions/Content</c>.
    /// </remarks>
    public static readonly Guid CompContentHeading =
        Guid.Parse("eb4bd93f-f9d1-44dd-b85e-d64b2084a3ad");

    /// <summary>
    /// <c>compContentText</c> — Reusable richtext body composition
    /// (<c>textBody</c>). Composed into Element Types that need their
    /// own paragraph of copy. Variations=Culture.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcontenttext.config</c>.
    /// Flow B — Ola 9.
    /// </remarks>
    public static readonly Guid CompContentText =
        Guid.Parse("71d74897-c807-452c-83c3-04c94fd1414b");

    /// <summary>
    /// <c>compContentCta</c> — Reusable Call-To-Action composition
    /// (<c>ctaLabel</c>, <c>ctaLink</c>, <c>ctaOpenInNewTab</c>).
    /// Composed into Element Types that invite an action.
    /// Variations=Culture (label + URL); <c>ctaOpenInNewTab</c>
    /// invariant.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcontentcta.config</c>.
    /// Flow B — Ola 9.
    /// </remarks>
    public static readonly Guid CompContentCta =
        Guid.Parse("92cb0070-0f4d-43a0-84a7-102f60dc41b4");

    /// <summary>
    /// <c>compContentMedia</c> — Reusable media reference composition
    /// (<c>mediaReference</c> + <c>mediaAlt</c> + <c>mediaCaption</c>).
    /// Alt mandatory per WCAG 1.1.1. Variations=Culture on all three.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcontentmedia.config</c>.
    /// Flow B — Ola 10. Folder <c>Compositions/Content/Media</c>.
    /// </remarks>
    public static readonly Guid CompContentMedia =
        Guid.Parse("e2a29901-8155-4d36-80ab-f42b2452a45b");

    /// <summary>
    /// <c>compContentMetadata</c> — Editorial (non-SEO) metadata:
    /// <c>metaKeywords</c> + <c>metaSummary</c>. For SEO use compSeo.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcontentmetadata.config</c>.
    /// Flow B — Ola 10. Folder <c>Compositions/Content/Meta</c>.
    /// </remarks>
    public static readonly Guid CompContentMetadata =
        Guid.Parse("84383010-4c98-4a2c-b67f-a347b00cde81");

    /// <summary>
    /// <c>compContentDate</c> — Editorial date (<c>contentDate</c>
    /// Nothing + <c>contentDateLabel</c> Culture). Distinct from
    /// Umbraco's native createDate/updateDate.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcontentdate.config</c>.
    /// Flow B — Ola 10.
    /// </remarks>
    public static readonly Guid CompContentDate =
        Guid.Parse("986da42d-9203-4270-8234-3f8255abdbdf");

    /// <summary>
    /// <c>compContentBadge</c> — Short status/category tag
    /// (<c>badgeLabel</c> Culture + <c>badgeVariant</c> Nothing).
    /// Distinct from <c>elementSynBadge</c> (CDN-hosted block).
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcontentbadge.config</c>.
    /// Flow B — Ola 11. Folder <c>Compositions/Content/Info</c>.
    /// </remarks>
    public static readonly Guid CompContentBadge =
        Guid.Parse("3e85c495-9fa5-430a-b982-b4bdeda74452");

    /// <summary>
    /// <c>compContentCollection</c> — Header metadata for item
    /// collections (ArticleList, BlogHighlight, FeatureGrid, etc.).
    /// Provides <c>collectionTitle</c> + <c>collectionPresentation</c>
    /// (grid/list/carousel key). Items themselves come from the
    /// composing Element Type's picker.
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcontentcollection.config</c>.
    /// Flow B — Ola 11. Folder <c>Compositions/Content/Collection</c>.
    /// </remarks>
    public static readonly Guid CompContentCollection =
        Guid.Parse("7f5ee960-dfc6-47f8-906e-c651444f45cf");

    /// <summary>
    /// <c>compContentEmbed</c> — Third-party embed reference
    /// (<c>embedUrl</c> Culture + <c>embedType</c> Nothing +
    /// <c>embedAspectRatio</c> Nothing). Distinct from
    /// <c>elementIntIframeHost</c> (standalone Element Type).
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/compcontentembed.config</c>.
    /// Flow B — Ola 11. Folder <c>Compositions/Content/Media</c>.
    /// </remarks>
    public static readonly Guid CompContentEmbed =
        Guid.Parse("85a37cab-3e4d-482a-b300-f4434c6eefbb");

    // ── DOM layer (capa 3) ─────────────────────────────────────────
    // Shareable universales para presentación. Todos Variations=Nothing
    // (styling = técnico, no traduce) salvo compDomAttributes.ariaLabel
    // que sí es Culture.

    /// <summary>
    /// <c>compDomClass</c> — CSS class + data attributes shareable
    /// universal (62 uses en legacy). Capa 3 DOM.
    /// </summary>
    public static readonly Guid CompDomClass =
        Guid.Parse("46367d43-269b-418d-b54d-075fcf6d658b");

    /// <summary>
    /// <c>compDomVariant</c> — design-system variant key (primary/
    /// secondary/ghost/outlined). 53 uses en legacy.
    /// </summary>
    public static readonly Guid CompDomVariant =
        Guid.Parse("e11a9feb-fa1c-4740-9481-3dce56748473");

    /// <summary>
    /// <c>compDomSpacing</c> — top/bottom/inline spacing scale keys.
    /// Opt-in para contenedores. 19 uses en legacy.
    /// </summary>
    public static readonly Guid CompDomSpacing =
        Guid.Parse("0a2edb7e-8555-4044-bebc-bf0fe37662f2");

    /// <summary>
    /// <c>compDomLayout</c> — layoutAlign + layoutDirection para
    /// contenedores flex/grid. 16 uses.
    /// </summary>
    public static readonly Guid CompDomLayout =
        Guid.Parse("06de133e-ab5f-4c56-970d-5aa8266e6334");

    /// <summary>
    /// <c>compDomAttributes</c> — ariaRole (Nothing) + ariaLabel
    /// (Culture) para accesibilidad. 12 uses.
    /// </summary>
    public static readonly Guid CompDomAttributes =
        Guid.Parse("1d5bafbb-59af-4002-8709-ebade1be0392");

    /// <summary>
    /// <c>compDomVisibility</c> — hide flags por breakpoint mobile/
    /// tablet/desktop. Unifica compVisibility legacy (SRP).
    /// </summary>
    public static readonly Guid CompDomVisibility =
        Guid.Parse("7a383458-6ea6-4784-a4d1-17f8d4b01073");

    // ── Behavior layer (capa 6, minimal) ──────────────────────────

    /// <summary>
    /// <c>compBehaviorFeatureFlag</c> — editor-facing gate por
    /// feature flag (ADR 0011). Renderer consulta IFeatureGate.
    /// </summary>
    public static readonly Guid CompBehaviorFeatureFlag =
        Guid.Parse("ed531586-b8a0-4c8c-be13-a7311017270e");

    // ── Element Types (primera familia SSR: text + action) ────────
    // Ola 13. Todos IsElement=true. Renderers bajo
    // Views/Partials/Elements/<Family>/<Name>.cshtml con wrappers en
    // Views/Partials/blockgrid/Components/ por convención Umbraco.

    /// <summary>
    /// <c>elementTextEyebrow</c> — Short caption text above a heading.
    /// Own prop <c>eyebrowText</c> Culture mandatory.
    /// </summary>
    public static readonly Guid ElementTextEyebrow =
        Guid.Parse("a8b1573f-427b-493f-89dd-b818ec95816a");

    /// <summary>
    /// <c>elementTextHeading</c> — Standalone heading block. All props
    /// come from compositions (compContentHeading + compDomAttributes).
    /// </summary>
    public static readonly Guid ElementTextHeading =
        Guid.Parse("6ad6f181-661a-48c9-8c36-22f8280f1a22");

    /// <summary>
    /// <c>elementTextLabel</c> — Categorical chip label.
    /// Own prop <c>labelText</c> Culture mandatory.
    /// </summary>
    public static readonly Guid ElementTextLabel =
        Guid.Parse("06590c83-bb73-4a5f-8421-ea37d884823b");

    /// <summary>
    /// <c>elementTextParagraph</c> — Plain text paragraph (TextArea).
    /// Own prop <c>paragraphText</c>. For rich formatting use
    /// <see cref="ElementTextRichtext"/> instead.
    /// </summary>
    public static readonly Guid ElementTextParagraph =
        Guid.Parse("034b4d6c-44ff-4ba6-bdc4-ad9325cd191b");

    /// <summary>
    /// <c>elementTextQuote</c> — Blockquote with body from
    /// compContentText and own <c>quoteAttribution</c> prop.
    /// </summary>
    public static readonly Guid ElementTextQuote =
        Guid.Parse("957e3f6a-b71b-441f-ae75-08d9e5574bcc");

    /// <summary>
    /// <c>elementTextRichtext</c> — Rich text block (TinyMCE). All
    /// props come from compositions.
    /// </summary>
    public static readonly Guid ElementTextRichtext =
        Guid.Parse("aad6c221-eca9-4956-8515-1fee67324dbd");

    /// <summary>
    /// <c>elementActionButton</c> — Primary action button with label,
    /// URL, target from compContentCta composition.
    /// </summary>
    public static readonly Guid ElementActionButton =
        Guid.Parse("2d8d712e-66ec-4052-a627-0ad8a68d0d38");

    /// <summary>
    /// <c>elementActionLink</c> — Text link (styled as link, not
    /// button). Adds compDomAttributes for ariaLabel.
    /// </summary>
    public static readonly Guid ElementActionLink =
        Guid.Parse("17c626f8-b24b-483f-b3e5-75581d44a7c7");

    // ── Media elements (Ola 14) ────────────────────────────────────

    public static readonly Guid ElementMediaAvatar =
        Guid.Parse("5b4f49ec-4609-4c06-89b8-5d5803cd17bb");

    public static readonly Guid ElementMediaIcon =
        Guid.Parse("0084598b-a3cb-4aa3-a15d-a7bcb594e11d");

    public static readonly Guid ElementMediaImage =
        Guid.Parse("82071ed1-299f-4eb8-83c1-b2769505ea09");

    public static readonly Guid ElementMediaVideo =
        Guid.Parse("530f72c5-7ee3-4a7b-b71a-16ac8da7e674");

    public static readonly Guid ElementMediaLogoItem =
        Guid.Parse("c954a483-d9e4-4143-9a2f-26cb08ee071a");

    public static readonly Guid ElementMediaGalleryItem =
        Guid.Parse("7f3434ae-503a-4594-b993-29eefe84a305");

    // ── Info elements (Ola 15) ─────────────────────────────────────

    public static readonly Guid ElementInfoBadge =
        Guid.Parse("f882450b-2c04-4dce-a584-1e0d8bccfef8");

    public static readonly Guid ElementInfoFaqItem =
        Guid.Parse("7152def0-2ea8-4cfc-bca3-792bd3ace8b2");

    public static readonly Guid ElementInfoFeature =
        Guid.Parse("a50d36ba-030f-4036-959d-b82361e6dbee");

    public static readonly Guid ElementInfoKeyValue =
        Guid.Parse("974cb4b8-0e13-4d26-9d57-0af23d827daa");

    public static readonly Guid ElementInfoStat =
        Guid.Parse("b1157cc1-762d-4c6f-a8f1-dc42d5bb891a");

    public static readonly Guid ElementInfoTestimonialItem =
        Guid.Parse("632796f2-a36c-4d3c-9ff4-bdd132725e24");

    public static readonly Guid ElementInfoTimelineItem =
        Guid.Parse("f845c403-0300-45e6-aa4f-1f1aa00cbdb4");

    // ── Action containers (Ola 17) ─────────────────────────────────

    /// <summary>
    /// <c>elementActionCtaGroup</c> — Container element grouping 1-4
    /// CTAs (elementActionButton or elementActionLink) via BlockList.
    /// First container pattern in the product; sets the precedent for
    /// future Info containers (FaqList, TimelineList) and Media
    /// containers (LogoCloud, Gallery).
    /// </summary>
    /// <remarks>
    /// Source: <c>uSync/v9/ContentTypes/elementactionctagroup.config</c>.
    /// Backed by <see cref="DataTypeKeys.BlockListCtaItems"/>.
    /// Ola 17.
    /// </remarks>
    public static readonly Guid ElementActionCtaGroup =
        Guid.Parse("5b95cd80-a64d-4867-8fc4-42358a4c5f68");

    // ── Info + Media containers (Ola 19) ───────────────────────────

    public static readonly Guid ElementInfoFaqList =
        Guid.Parse("b5f9e196-0c48-4ce4-8ef5-a7b6551b3ebc");

    public static readonly Guid ElementMediaLogoCloud =
        Guid.Parse("29e37dfc-a27d-4034-9e29-61e613f8f55c");

    public static readonly Guid ElementInfoTestimonialCarousel =
        Guid.Parse("f1146138-039e-4f03-82aa-acdac63a6032");

    public static readonly Guid ElementMediaGallery =
        Guid.Parse("2fa2ee67-27d2-46ab-927e-8b2bd99067e5");

    public static readonly Guid ElementInfoTimelineList =
        Guid.Parse("e3765317-f0b9-4ff3-9699-f17ccbb190d3");

    // ── Structural Element Types (Ola 20) ──────────────────────────

    /// <summary>
    /// <c>elementStructSection</c> — Semantic section container with
    /// BlockGrid children. Landmark for accessibility.
    /// </summary>
    public static readonly Guid ElementStructSection =
        Guid.Parse("755df659-4c07-45d5-a394-092b858ca50f");

    /// <summary>
    /// <c>elementStructContainer</c> — Generic div wrapper with
    /// width constraint.
    /// </summary>
    public static readonly Guid ElementStructContainer =
        Guid.Parse("4a9392cc-9acb-40a0-8df8-225060478461");

    /// <summary>
    /// <c>elementStructGrid</c> — CSS grid with configurable columns
    /// (2-6, default 3).
    /// </summary>
    public static readonly Guid ElementStructGrid =
        Guid.Parse("20c6a4c9-c8ed-4349-bdad-2935a49e7442");

    /// <summary>
    /// <c>elementStructColumn</c> — Explicit column with columnSpan
    /// (1-12).
    /// </summary>
    public static readonly Guid ElementStructColumn =
        Guid.Parse("bee4e11a-a419-449f-8a76-d2fd691b1a0d");

    /// <summary>
    /// <c>elementStructStack</c> — Flex container with gap;
    /// direction from compDomLayout.
    /// </summary>
    public static readonly Guid ElementStructStack =
        Guid.Parse("2c21bf8b-540b-4e78-80f3-584d944f7bf5");

    /// <summary>
    /// <c>elementStructDivider</c> — Horizontal rule atomic. Own
    /// prop dividerStyle (line/dashed/dotted/gradient/shadow).
    /// Variations=Nothing (decorative).
    /// </summary>
    public static readonly Guid ElementStructDivider =
        Guid.Parse("0b6e8259-6a03-4be2-ae28-af59f1987f16");

    /// <summary>
    /// <c>elementStructSpacer</c> — Invisible spacer atomic. Own
    /// prop spacerSize (xs-2xl). Variations=Nothing.
    /// </summary>
    public static readonly Guid ElementStructSpacer =
        Guid.Parse("ea43b0d7-babc-42c3-984a-cf7ba60bc456");

    // ── Corp Element Types (Ola 21) ────────────────────────────────

    /// <summary>
    /// <c>elementCorpAlertBar</c> — Site-wide announcement banner
    /// (alertMessage + optional CTA + optional dismiss button).
    /// Composes compDomClass + compDomVariant (info/warning/success/
    /// error) + compDomVisibility. Variations=Culture.
    /// </summary>
    public static readonly Guid ElementCorpAlertBar =
        Guid.Parse("989dcef3-b045-4ad7-8ac8-a3b848511c6e");

    /// <summary>
    /// <c>elementCorpContactInfo</c> — Corporate contact block
    /// (email + phone + address). Atomic; each field optional.
    /// </summary>
    public static readonly Guid ElementCorpContactInfo =
        Guid.Parse("2fe68566-cd4e-495a-9a31-abb7d0fb77fc");

    /// <summary>
    /// <c>elementCorpMissionBlock</c> — Mission/vision/values
    /// declaration. Composed: compContentHeading + compContentText +
    /// compContentMedia (optional). No own props.
    /// </summary>
    public static readonly Guid ElementCorpMissionBlock =
        Guid.Parse("2717b9e7-debe-4354-8dfd-780f88f1842c");

    /// <summary>
    /// <c>elementCorpSocialShare</c> — Social share button group.
    /// Uses current page URL + title (UmbracoContext). Own prop
    /// platforms (multi-dropdown of DTSelectSharePlatform). Variations=Nothing.
    /// </summary>
    public static readonly Guid ElementCorpSocialShare =
        Guid.Parse("d2914c34-2485-4a49-b57d-14555a644653");

    /// <summary>
    /// <c>elementCorpNewsletterForm</c> — Newsletter subscription
    /// form POSTing to an external endpoint (Mailchimp, SendGrid,
    /// Synergos.API). Own props: formTitle, formSubtitle,
    /// placeholderText, submitLabel (Culture) + formEndpoint (Nothing).
    /// </summary>
    public static readonly Guid ElementCorpNewsletterForm =
        Guid.Parse("bf3e7cd0-3ba8-4188-83dc-c07565593af6");

    /// <summary>
    /// <c>elementCorpBannerSlider</c> — Carousel of banner slides.
    /// Slides BlockList of elementMediaImage (mandatory 1+).
    /// Autoplay flag (Nothing). JS hydration; SSR emits all slides
    /// inline for no-JS fallback.
    /// </summary>
    public static readonly Guid ElementCorpBannerSlider =
        Guid.Parse("2cb0b5b9-91e6-4567-b4dc-0d95e27b4c40");

    // ── Comp Element Types (Ola 22) ────────────────────────────────

    /// <summary>
    /// <c>elementCompCard</c> — Atomic composite card (heading + text
    /// + media + cta, all from compositions). No own props.
    /// </summary>
    public static readonly Guid ElementCompCard =
        Guid.Parse("c646696c-8819-4630-bc7a-121f0839bb16");

    /// <summary>
    /// <c>elementCompCtaBanner</c> — Compact heading + CTA banner.
    /// No own props; uses compContentHeading + compContentCta.
    /// </summary>
    public static readonly Guid ElementCompCtaBanner =
        Guid.Parse("5c21b68f-a4d6-4ef4-aba0-771517acb556");

    /// <summary>
    /// <c>elementCompFeatureGrid</c> — Container iterating
    /// elementInfoFeature via BlockList (mandatory 1+). Backing
    /// <see cref="DataTypeKeys.BlockListFeatureItems"/>.
    /// </summary>
    public static readonly Guid ElementCompFeatureGrid =
        Guid.Parse("178778fd-9193-4a43-a48d-5518c4a3f720");

    /// <summary>
    /// <c>elementCompHero</c> — Full-width landing hero. Composes
    /// content + dom compositions. Own prop ctaItems BlockList
    /// (reuses DT.BlockList.CtaItems: Button | Link).
    /// </summary>
    public static readonly Guid ElementCompHero =
        Guid.Parse("65a8b66a-be4f-4722-a5b2-42fc57a73ebb");

    /// <summary>
    /// <c>elementCompMediaTextSplit</c> — 50/50 media+text layout.
    /// Own prop mediaOnRight (TrueFalse Nothing) toggles column order.
    /// </summary>
    public static readonly Guid ElementCompMediaTextSplit =
        Guid.Parse("3a6f8ea9-7593-4ced-885d-4c01cb97eaea");

    // ── Form Element Types (Ola 23, ADR 0018 dual path) ───────────
    //
    // Custom path: elementFormContainer + elementFormField build a
    // native SSR form that POSTs to an external endpoint
    // (Formspree / Netlify Forms / Synergos.API).
    //
    // Bridge path: elementFormEmbed renders an iframe hosting an
    // external form (Typeform / Jotform / Umbraco.Forms if adopted).
    //
    // elementFormField is NOT exposed at Editorial BG top-level —
    // only instantiable inside elementFormContainer.fields via
    // DT.BlockList.FormFields.

    /// <summary>
    /// <c>elementFormContainer</c> — Custom SSR form. Props:
    /// formTitle (Culture), formEndpoint (Nothing mandatory URL),
    /// submitLabel (Culture), fields (BlockList 1+ FormField).
    /// </summary>
    public static readonly Guid ElementFormContainer =
        Guid.Parse("15a5e7b3-b97c-491b-91de-fa7c934e4bc6");

    /// <summary>
    /// <c>elementFormField</c> — Single form field. Props:
    /// fieldLabel (Culture), fieldName (Nothing slug-validated),
    /// fieldType (Nothing enum text/email/tel/number/textarea/date/url),
    /// fieldRequired, fieldPlaceholder (Culture), fieldHelpText
    /// (Culture).
    /// </summary>
    public static readonly Guid ElementFormField =
        Guid.Parse("a651afde-3d2c-4ad4-ad49-7e4b8912f9ad");

    /// <summary>
    /// <c>elementFormEmbed</c> — iframe bridge to an external form
    /// renderer. Props: embedUrl (Nothing URL), embedTitle (Culture,
    /// a11y mandatory), embedHeight (Nothing numeric default 600).
    /// </summary>
    public static readonly Guid ElementFormEmbed =
        Guid.Parse("9009d554-cafa-4d15-b177-13bc02650aaa");

    // ── Nav Element Types (Ola 24, ADR 0019) ───────────────────────
    //
    // Navigation is modeled as a flat <nav><ul> group containing
    // NavItem links. Deep menus should be composed of sibling
    // elementNavGroup blocks (one per section) rather than recursive
    // nesting — keeps SSR + a11y simple. See ADR 0019 Nav §3.
    //
    // elementNavItem is NOT exposed at Editorial BG top-level — only
    // instantiable inside elementNavGroup.navItems via
    // DT.BlockList.NavItems.

    /// <summary>
    /// <c>elementNavGroup</c> — nav section (&lt;nav&gt;). Props:
    /// navHeading (Culture optional), navItems (BlockList 1+ NavItem).
    /// </summary>
    public static readonly Guid ElementNavGroup =
        Guid.Parse("fe2123d5-f4df-406a-b064-48dd55bd59d5");

    /// <summary>
    /// <c>elementNavItem</c> — single link. Props: navLabel (Culture),
    /// navLink (MultiUrlPicker — localized paths allowed), navOpenInNewTab.
    /// </summary>
    public static readonly Guid ElementNavItem =
        Guid.Parse("1beb4eae-34bd-4eba-95e0-a2183fbac8ba");

    // ── Corp mega-batch (Ola 24) — TabGroup/TabPanel/DataTable/MapEmbed

    /// <summary>
    /// <c>elementCorpTabGroup</c> — Container of tab panels with
    /// ARIA tablist semantics. Props: tabsTitle (Culture), tabs
    /// (BlockList 1+ TabPanel via DT.BlockList.TabPanels).
    /// </summary>
    public static readonly Guid ElementCorpTabGroup =
        Guid.Parse("945c17d6-8efa-41ba-9952-015caae6ff6b");

    /// <summary>
    /// <c>elementCorpTabPanel</c> — single panel (tabLabel + richtext
    /// tabContent). Hidden from Editorial BG top-level.
    /// </summary>
    public static readonly Guid ElementCorpTabPanel =
        Guid.Parse("0843bc73-3b11-48d2-bf99-c9a4a327a060");

    /// <summary>
    /// <c>elementCorpDataTable</c> — CSV-backed accessible table.
    /// Props: tableCaption (Culture), tableData (Culture mandatory
    /// TextArea CSV). Complex tables → elementIntIframeHost with
    /// Datawrapper/Flourish.
    /// </summary>
    public static readonly Guid ElementCorpDataTable =
        Guid.Parse("5d8de320-6f3c-49a2-9dee-c1a517d66a3e");

    /// <summary>
    /// <c>elementCorpMapEmbed</c> — Map iframe (Google Maps / OSM /
    /// Mapbox). Props: mapUrl (Nothing https), mapTitle (Culture
    /// mandatory WCAG), mapHeight (Nothing default 450).
    /// </summary>
    public static readonly Guid ElementCorpMapEmbed =
        Guid.Parse("fb92f569-2a4e-4ac3-a114-6f62e460abfd");

    // ── SynHost batch A (Ola 26, ADR 0015) ─────────────────────────
    //
    // 10 additional elementSyn* blocks following the pilot pattern
    // (compIntegration composition + <synergos-*> custom element +
    // ISynHostEmitter + IBundleRegistryClient runtime resolution).
    //
    // Render until CDN registry provides real bundles relies on the
    // StubBundleRegistryClient — the custom elements render empty
    // until a bundle exists, which is by design.

    public static readonly Guid ElementSynSpacer =
        Guid.Parse("9b38e09f-1507-4da9-820f-6796f4bec759");

    public static readonly Guid ElementSynSeparator =
        Guid.Parse("e1fc35de-ced4-4337-9a0e-7d91188eec57");

    public static readonly Guid ElementSynIconLabel =
        Guid.Parse("76e01860-3664-4606-94ed-45c16229b9ef");

    public static readonly Guid ElementSynProgressBar =
        Guid.Parse("4def9a2d-5d0b-44f5-a85f-2d1713129c34");

    public static readonly Guid ElementSynRatingStars =
        Guid.Parse("1c1e7a41-ca10-4264-b52a-422e79ea4daf");

    public static readonly Guid ElementSynStatTicker =
        Guid.Parse("4051fd78-db88-43a8-98db-c96fa502d215");

    public static readonly Guid ElementSynCountdownClock =
        Guid.Parse("4a83b837-fea0-4e1d-8ac7-53ab7d82e2bd");

    public static readonly Guid ElementSynTooltip =
        Guid.Parse("6e762bad-84ce-4430-92cb-9716c0d0c7c1");

    public static readonly Guid ElementSynTag =
        Guid.Parse("1923996b-f282-49ac-89c5-25f31bcda9d9");

    public static readonly Guid ElementSynSearchBox =
        Guid.Parse("d2c5c575-33a4-4fbf-8fe6-65f9d41e50ef");

    // ── SynHost batch B (Ola 27, ADR 0015) ─────────────────────────
    //
    // 10 additional elementSyn* composite/interactive media blocks.
    // Only added to DT.BlockGrid.Editorial under "Syn (CDN)" group —
    // SynPilot DataType preserved as pilot-scope only (3 pilot + 10
    // batch A).

    public static readonly Guid ElementSynHeroBanner =
        Guid.Parse("637eccc8-2c40-4b65-b2f6-8b7694e10c0d");

    public static readonly Guid ElementSynCarousel =
        Guid.Parse("84f1d806-a14a-4e76-aa3f-1aa6112b5ea9");

    public static readonly Guid ElementSynVideoPlayer =
        Guid.Parse("58039b72-11a2-461c-be0b-cca664c1421e");

    public static readonly Guid ElementSynAudioPlayer =
        Guid.Parse("196adec6-504a-4d26-836a-0899e06c9664");

    public static readonly Guid ElementSynLightboxGallery =
        Guid.Parse("bc1dedcf-a91c-4db6-a65c-fa6bf48dec53");

    public static readonly Guid ElementSynTimeline =
        Guid.Parse("66976d3e-0d73-4634-8f69-4744efd30724");

    public static readonly Guid ElementSynBreadcrumb =
        Guid.Parse("ae8c4bff-30d0-448b-8e5d-741f22983760");

    public static readonly Guid ElementSynCookieConsent =
        Guid.Parse("23efc1d2-9f83-4ba4-a61e-e545b0852110");

    public static readonly Guid ElementSynNotificationToast =
        Guid.Parse("81d1f39e-1fc1-4edd-83aa-32191e64b125");

    public static readonly Guid ElementSynModalTrigger =
        Guid.Parse("102c71af-4d8a-4bb0-980c-b9f4cb0df404");

    // ── SynHost batch C (Ola 28, ADR 0015) ─────────────────────────
    //
    // 10 interactive widgets + data viz + utility blocks.

    public static readonly Guid ElementSynDropdown =
        Guid.Parse("1d22d520-7f56-4e20-b3bc-502381bfa161");

    public static readonly Guid ElementSynDatePicker =
        Guid.Parse("5367d42f-1fd0-4e40-b7ab-a68ce226f2a8");

    public static readonly Guid ElementSynFileUploader =
        Guid.Parse("bf0601d7-277d-4671-b393-fa86fcf4700e");

    public static readonly Guid ElementSynChartBar =
        Guid.Parse("d94ca296-8867-4cab-8f08-75ef1cb4455a");

    public static readonly Guid ElementSynKpiCard =
        Guid.Parse("51b3896b-0b23-4a83-8993-0efee9cd5fe8");

    public static readonly Guid ElementSynCodeBlock =
        Guid.Parse("baee0724-4cd4-4a2e-bf96-c9bf570b5e78");

    public static readonly Guid ElementSynCopyButton =
        Guid.Parse("1b45b734-faa2-41af-8337-6023a805c608");

    public static readonly Guid ElementSynShareBar =
        Guid.Parse("b4d98500-e6b0-463f-adde-8adc8174a23f");

    public static readonly Guid ElementSynMapPin =
        Guid.Parse("f0b04253-d9cb-49b8-83d8-01801597daed");

    public static readonly Guid ElementSynScrollTop =
        Guid.Parse("43d984b3-6078-4cec-829b-a63d077ca9f0");

    // ── SynHost batch D (Ola 29, ADR 0015) ─────────────────────────

    public static readonly Guid ElementSynColorPicker =
        Guid.Parse("794c62f6-1ab1-4cba-8011-d62b0850a824");

    public static readonly Guid ElementSynSignaturePad =
        Guid.Parse("0986d2a6-6d2b-4efd-8fed-14df36c2e35c");

    public static readonly Guid ElementSynPoll =
        Guid.Parse("db4d313c-d451-4055-b1a5-44ebfbd646e8");

    public static readonly Guid ElementSynTourGuide =
        Guid.Parse("fd7df0b0-f0c0-4c03-ba38-84b2e51c6a2b");

    public static readonly Guid ElementSynRangeSlider =
        Guid.Parse("27e83784-0055-4d44-ab51-f0d3ed6a679b");

    public static readonly Guid ElementSynNotificationCenter =
        Guid.Parse("8ecc2da5-ca2f-43f3-a3da-8ef40b354954");

    public static readonly Guid ElementSynCommentsWidget =
        Guid.Parse("eecdf82e-1fe0-4e48-b334-cc9a5c51c9a6");

    public static readonly Guid ElementSynSocialProof =
        Guid.Parse("ea816762-376c-436c-8be6-4700cdfb9db9");

    public static readonly Guid ElementSynTestimonialCarousel =
        Guid.Parse("8fc6922d-7e96-4a0f-8535-eb55fe1b53ed");

    public static readonly Guid ElementSynPagination =
        Guid.Parse("45462c77-7026-4191-b1a7-6b820a2fc679");

    public static readonly Guid ElementSynAccordion =
        Guid.Parse("3d5d7863-eb51-43d4-a887-c1341a787ceb");

    public static readonly Guid ElementSynTabs =
        Guid.Parse("de7d47c3-518e-4a28-b20b-8077ff7bf9e8");

    public static readonly Guid ElementSynOEmbed =
        Guid.Parse("d834fd85-0e8b-4a1e-9a4c-fa1c914eec9a");

    public static readonly Guid ElementSynAvatarGroup =
        Guid.Parse("af9cb2a6-56e8-4818-b7fb-fe723e642d6d");

    public static readonly Guid ElementSynFab =
        Guid.Parse("faee0eae-8c1b-48a3-a5ed-e3096006c35c");

    // ── SynHost batch E FINAL (Ola 30, ADR 0015) ───────────────────
    //
    // 23 blocks para cerrar elementSyn* al 100% (71/71). Forms/inputs +
    // overlays + data display + embeds + utility.

    public static readonly Guid ElementSynAutocomplete =
        Guid.Parse("4ac9c915-c376-4f73-8f5a-294f3f0e7480");

    public static readonly Guid ElementSynSelectMulti =
        Guid.Parse("8779fad5-d9f1-49f9-8507-b4aec9196d94");

    public static readonly Guid ElementSynOtpInput =
        Guid.Parse("0d6fe720-073c-4f16-a520-b3665915e05c");

    public static readonly Guid ElementSynFormStepper =
        Guid.Parse("805dafc6-0b8b-4ff2-8f02-f43ace8ff8fd");

    public static readonly Guid ElementSynDropzone =
        Guid.Parse("1b40cbc3-1bde-4909-9792-cede523ca704");

    public static readonly Guid ElementSynAvatarUpload =
        Guid.Parse("6907ec32-4034-41e5-969c-5cce8ea26fd6");

    public static readonly Guid ElementSynDrawer =
        Guid.Parse("6ef80673-ded5-42cd-a3f5-ce3be414bab6");

    public static readonly Guid ElementSynPopover =
        Guid.Parse("6ccdf2df-a092-4d8f-9528-b30fb5cb4bd8");

    public static readonly Guid ElementSynSkeleton =
        Guid.Parse("f4b83407-454e-40a6-a84b-f1cc8880300d");

    public static readonly Guid ElementSynSplitter =
        Guid.Parse("5cbe20b2-0a94-487c-8bf5-300347be2f8b");

    public static readonly Guid ElementSynStepper =
        Guid.Parse("ac0739d0-83a3-4024-ada8-b45af8c2e1ca");

    public static readonly Guid ElementSynDataGrid =
        Guid.Parse("aa558080-4f20-4a7d-8bb7-cef8c52439b4");

    public static readonly Guid ElementSynTreeView =
        Guid.Parse("a9b5ca26-b4ac-4ca5-8828-348a5d87ed82");

    public static readonly Guid ElementSynTimelineHorizontal =
        Guid.Parse("f56b46e4-75db-4ac2-8a92-4bbfe002471f");

    public static readonly Guid ElementSynCalendar =
        Guid.Parse("0c92d91b-9ffd-428f-a89a-9e78056c50b2");

    public static readonly Guid ElementSynCountdownDigital =
        Guid.Parse("5145e257-5eb1-4a2f-a0b0-b585c80975d1");

    public static readonly Guid ElementSynQuoteAnimated =
        Guid.Parse("39359212-0766-4199-9543-9184be528dc9");

    public static readonly Guid ElementSynBadgeGroup =
        Guid.Parse("899e2c0c-93e0-4663-9893-be6b283e4ae5");

    public static readonly Guid ElementSynLivestream =
        Guid.Parse("64ae0d5a-2de8-41a6-9dc1-bf4652538648");

    public static readonly Guid ElementSynColorSwatches =
        Guid.Parse("7ab7b363-b665-4418-847b-10d6b719588b");

    public static readonly Guid ElementSynToastCenter =
        Guid.Parse("80e25e27-804a-47ac-a5a5-b9b360a4a6fe");

    public static readonly Guid ElementSynRichTooltip =
        Guid.Parse("4c9855b4-c33b-4f40-8453-e12a3e35653b");

    public static readonly Guid ElementSynQrCode =
        Guid.Parse("fc36505d-ddef-4161-aadb-8098623982b6");

    // ── Platform/Settings (Ola 31, ADR 0020) ───────────────────────
    //
    // Settings tree separado del content tree de siteRoot. Multi-brand
    // soportado vía compBranding.brandKey; IBrandingProvider resuelve
    // settings por brand request.

    /// <summary>
    /// <c>compBranding</c> — Composition for multi-brand identification.
    /// Props: brandKey (Nothing slug mandatory), brandDisplayName
    /// (Culture mandatory). Composed by all settings DocTypes.
    /// </summary>
    public static readonly Guid CompBranding =
        Guid.Parse("5e3ba572-dcf1-4752-b256-d11a79426f6d");

    /// <summary>
    /// <c>settingsRoot</c> — Root container of the Settings tree.
    /// AllowAtRoot=true. Structure allows themeSettings + siteConfigSettings
    /// + featureFlagsSettings as children.
    /// </summary>
    public static readonly Guid SettingsRoot =
        Guid.Parse("5af43879-6f53-4a72-b71e-9d77093b9921");

    /// <summary>
    /// <c>themeSettings</c> — Branding theme (colors, fonts, logos,
    /// favicon) per brand. Composes compBranding.
    /// </summary>
    public static readonly Guid ThemeSettings =
        Guid.Parse("04fa0739-c87d-4737-96af-44d37d45ffd3");

    /// <summary>
    /// <c>siteConfigSettings</c> — Site-wide config per brand: analytics,
    /// GTM, SEO defaults, policy URLs. Composes compBranding.
    /// </summary>
    public static readonly Guid SiteConfigSettings =
        Guid.Parse("ecbd95d0-4e00-451e-90ec-ebadc5fb0773");

    /// <summary>
    /// <c>featureFlagsSettings</c> — Feature flag overrides per brand
    /// (flagsJson). Consumed by IFeatureGate priority over appsettings.
    /// Composes compBranding.
    /// </summary>
    public static readonly Guid FeatureFlagsSettings =
        Guid.Parse("729b8b9a-3667-4fcd-967a-a8535cc017a9");

    // ── Blog skeleton (Ola 32) ─────────────────────────────────────

    public static readonly Guid CompTagging =
        Guid.Parse("d438906f-3698-4f7a-8371-3a9a856b845b");

    public static readonly Guid PostPage =
        Guid.Parse("ce854792-be23-4796-8851-c2a281fe08c8");

    public static readonly Guid PostCategoryPage =
        Guid.Parse("833d51b0-1029-473c-93b2-b1f455fff76d");

    public static readonly Guid ElementCompArticleList =
        Guid.Parse("a58bb4ad-d222-4e90-95b1-48408d516bf4");

    public static readonly Guid ElementCompBlogHighlight =
        Guid.Parse("84c34c2c-3faa-41a7-a409-dabf5d09c8db");

    // ── Shop skeleton (Ola 33) ─────────────────────────────────────

    /// <summary>
    /// <c>productPage</c> — Product DocType. Composes compCoreBase +
    /// compSeo + compTagging. Props: productSku (Nothing), productName
    /// (Culture), productDescription (Culture richtext), productPriceBase
    /// (Nothing decimal), productImages (Culture MediaPicker3 multi),
    /// productInStock (Nothing flag), productVariantsJson (Culture).
    /// </summary>
    public static readonly Guid ProductPage =
        Guid.Parse("7183ebd0-08be-415d-a1f7-e4a6efceeb9d");

    /// <summary>
    /// <c>productCategoryPage</c> — Product category container.
    /// IsListView=true. Structure allows productPage children.
    /// </summary>
    public static readonly Guid ProductCategoryPage =
        Guid.Parse("91593852-654e-46e0-9eae-e1507cde0e9c");

    public static readonly Guid ElementShopProductCard =
        Guid.Parse("59470582-1df8-4a0c-b3c4-80fadccbb7ed");

    public static readonly Guid ElementShopPriceDisplay =
        Guid.Parse("9b38832b-2ec9-44bd-b80d-f4c1f84b9828");

    public static readonly Guid ElementShopQuantitySelector =
        Guid.Parse("6ea62ca6-1bcc-4194-ad07-ae5a8dc8996d");

    public static readonly Guid ElementShopVariantPicker =
        Guid.Parse("0bc4e33a-8e3a-45b1-98df-cd8e006e9898");

    public static readonly Guid ElementShopCartItem =
        Guid.Parse("45ba06ed-e07a-4113-b2bb-fdc15171472b");

    public static readonly Guid ElementShopCartSummary =
        Guid.Parse("913a7ede-b119-4bcd-8454-77ce4e1e20ca");

    // ── Shared Content / Reusable Block (Ola 34) ──────────────────

    /// <summary>
    /// <c>sharedContentFolder</c> — Container para reusableBlock.
    /// AllowAtRoot; tree separado paralelo a siteRoot + settingsRoot.
    /// </summary>
    public static readonly Guid SharedContentFolder =
        Guid.Parse("9a1134b1-c973-4527-b988-f29f1457ad5c");

    /// <summary>
    /// <c>reusableBlock</c> — Bloque de contenido reutilizable con
    /// bodyBlocks (DT.BlockGrid.Editorial). Consumido desde pages
    /// via picker/embed. Props: blockTitle, blockNotes, bodyBlocks.
    /// </summary>
    public static readonly Guid ReusableBlock =
        Guid.Parse("907840c2-4bd1-4ef8-8181-c4abea0e8a9a");

    // ── Members module (Ola 35) ────────────────────────────────────
    //
    // Schema-only — middleware C# Members auth (IMemberManager, route
    // gating) pendiente para ola runtime posterior.

    /// <summary>
    /// <c>compMemberGating</c> — Composition para marcar DocTypes como
    /// member-gated. Props: requiresAuth (flag) + allowedRolesCsv.
    /// </summary>
    public static readonly Guid CompMemberGating =
        Guid.Parse("0398491c-ac46-4c7b-b61f-4e0949c4fa85");

    /// <summary>
    /// <c>memberProfilePage</c> — Profile page pública. Composes
    /// compCoreBase + compSeo + compMemberGating. Props: displayName,
    /// bio (richtext), avatarUrl (MediaPicker3).
    /// </summary>
    public static readonly Guid MemberProfilePage =
        Guid.Parse("c167bb4b-d3ad-414e-8a2e-fef3bf06f97f");

    public static readonly Guid ElementMemberLogin =
        Guid.Parse("1cbfc5c4-9fac-492a-8f87-aeda29e4397b");

    public static readonly Guid ElementMemberLogout =
        Guid.Parse("48c8b4b1-15d9-4d94-bfcc-52eb6d9ec595");

    public static readonly Guid ElementMemberProfile =
        Guid.Parse("e4a1f1d5-9fd9-4f92-9f85-c324291ad3af");

    /// <summary>
    /// <c>elementMemberGate</c> — BlockGrid wrapper con auth check.
    /// gatedBlocks (BlockGrid Editorial) + loginPromptMessage.
    /// </summary>
    public static readonly Guid ElementMemberGate =
        Guid.Parse("877db10c-7953-4902-8c85-e8b4ea55246d");

    // ── Schema completion (Ola 36) ─────────────────────────────────
    // Blog author · Multi-tenancy · Shop completion · Flow module

    /// <summary>
    /// <c>compContentAuthor</c> — Composition de autoría editorial
    /// (authorName, authorRole, authorAvatar). Culture.
    /// </summary>
    public static readonly Guid CompContentAuthor =
        Guid.Parse("91e03cae-9044-45e0-a328-62e9d369db64");

    /// <summary>
    /// <c>authorPage</c> — Página pública de autor con bio richtext
    /// + socialLinksJson. Composes compContentAuthor.
    /// </summary>
    public static readonly Guid AuthorPage =
        Guid.Parse("acb0cccc-08c9-4608-8bac-6b9a7aacc901");

    /// <summary>
    /// <c>compTenant</c> — Composition multi-tenancy. Props: tenantKey
    /// (Nothing slug mandatory) + tenantDisplayName (Culture).
    /// </summary>
    public static readonly Guid CompTenant =
        Guid.Parse("6fac54b2-6604-4863-8929-cd6b1a09c5f2");

    /// <summary>
    /// <c>tenantRoot</c> — Root multi-tenancy. AllowAtRoot. Composes
    /// compTenant. Structure allows siteRoot + settingsRoot +
    /// sharedContentFolder. Middleware runtime pendiente.
    /// </summary>
    public static readonly Guid TenantRoot =
        Guid.Parse("7f4937bc-d6dd-4d5d-b09a-6ae1fcde4a87");

    public static readonly Guid ElementShopProductDetail =
        Guid.Parse("6e556758-8b43-40e2-b8de-2b9b47f6f9b7");

    public static readonly Guid ElementShopProductGrid =
        Guid.Parse("2077b90e-0bee-4c30-934a-5fd4ea089441");

    /// <summary>
    /// <c>flowDefinition</c> — Flujo editorial (survey, wizard,
    /// onboarding). Composes compCoreBase. IsListView. Structure
    /// allows flowStep. Props: flowKey (slug), flowTitle, flowDescription,
    /// maxSteps.
    /// </summary>
    public static readonly Guid FlowDefinition =
        Guid.Parse("4a23719f-d73b-49b3-8509-da108a7c5a92");

    /// <summary>
    /// <c>flowStep</c> — Step individual dentro de flowDefinition.
    /// Props: stepKey, stepLabel, stepContent (TinyMCE), isTerminal.
    /// </summary>
    public static readonly Guid FlowStep =
        Guid.Parse("3fb9c047-fb4c-4729-97f1-f39d03fd4f97");

    public static readonly Guid ElementFlowTrigger =
        Guid.Parse("40de7d88-3a34-4c50-b446-6ff98bd17e04");

    public static readonly Guid ElementFlowProgress =
        Guid.Parse("57c35e5a-983e-499a-8154-38aebca79c97");
}
