namespace Synergos.CMS.Application.Dto.Constants;

/// <summary>
/// Stable GUID keys for Umbraco Content Types (Compositions, Element
/// Types, Document Types) that have been exported to
/// <c>Synergos.CMS.Web/uSync/v9/ContentTypes/</c>.
/// </summary>
/// <remarks>
/// Per ADR 0008, uSync XMLs are the source of truth; this class is a
/// typed reference for code that needs to resolve types by GUID.
///
/// GUID assignment policy:
/// <list type="bullet">
///   <item>GUIDs are <b>generated by Umbraco</b> when the type is
///   created in the backoffice. uSync captures the value on export
///   (feature <c>feedback_no_preassigned_guids_usync</c> in agent memory).</item>
///   <item>Constants are added here <b>after</b> the uSync XML exists —
///   never before. The quadruple verification from
///   <c>MIGRATION_GUARDRAILS §6.2</c> runs on the real captured GUID.</item>
///   <item>The Epic Fail 2 prefix convention (<c>b1*-b8*</c> Compositions,
///   <c>c3*-ce*</c> Element Types, <c>d2*-d6*</c> Document Types) is a
///   <b>historical reference</b> (see <c>history_guid_registry_epicfail2</c>
///   in agent memory), not a rule. Current GUIDs are whatever Umbraco
///   generates; no attempt to force them into legacy ranges.</item>
/// </list>
/// </remarks>
public static class ContentTypeKeys
{
    /// <summary>
    /// <c>compSeo</c> — Composition providing the <c>seoTitle</c>
    /// property. Composed into Document Types that need SEO metadata;
    /// not instantiable as Content (<c>IsElement=false</c>).
    /// </summary>
    /// <remarks>
    /// Source: <c>Synergos.CMS.Web/uSync/v9/ContentTypes/compseo.config</c>.
    /// GUID generated by Umbraco on backoffice save (Ola 4 of the
    /// migration plan). Minor visual-naming debt tracked in
    /// <c>refactor-docs/migration/03-migration-inventory.md</c>
    /// (Ola 4 execution log) — does not affect the contract of the
    /// alias / GUID used from code.
    /// </remarks>
    public static readonly Guid CompSeo =
        Guid.Parse("85e75635-b950-4583-b5ca-2a51c08892e3");
}
